### ISSUE TITLE
Installing on HassOS

### ISSUE THREAD

**Issue by Wolfieeewolf** [Den901/ha_came#4]
How do I go about installing this on HassOS?

I can't use pip and there is no HACS integration as of yet so I'm stuck at the first step.

**Comment by Den901** [comment]
Hi Wolfiee, you have to install the library in to the container where hass os is stored

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Wolfieee ***@***.***>
Inviato: Friday, November 10, 2023 12:48:15 PM
A: Den901/ha_came ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Den901/ha_came] Installing on HassOS (Issue #4)


How do I go about installing this on HassOS?

I can't use pip and there is no HACS integration as of yet so I'm stuck at the first step.

**Comment by Wolfieeewolf** [comment]
How do i access the container? I have no idea how to do that. I have looked at SSH'ing into the container but most of what i'm finding if for people who have HA setup on VM's. I have mine setup using the Home Assistant Operating System running on an old HP thin client. 

I don't understand how to access the containers and install the pycame python script. The rest I can do via the HA GUI

**Comment by Den901** [comment]
I think that the problem is the hassos… it had a “temporary” environment, so you can’t instal directly on it. I suggest to switch the distro with a unix distribution (under docker or similar)

Inviato da Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: Wolfieee ***@***.***>
Inviato: Monday, November 13, 2023 4:32:54 AM
A: Den901/ha_came ***@***.***>
Cc: Danny Mauro ***@***.***>; Comment ***@***.***>
Oggetto: Re: [Den901/ha_came] Installing on HassOS (Issue #4)


How do i access the container? I have no idea how to do that. I have looked at SSH'ing into the container but most of what i'm finding if for people who have HA setup on VM's. I have mine setup using the Home Assistant Operating System running on an old HP thin client.

I don't understand how to access the containers and install the pycame python script. The rest I can do via the HA GUI

**Comment by Wolfieeewolf** [comment]
Thank I'll see how I go with that.
